version: '2'
services:
    teachit-app:
        image: teachit
        external_links:
            - teachit-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/teachit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    teachit-mysql:
        extends:
            file: mysql.yml
            service: teachit-mysql
